# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'v.$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: $(pool)
    steps:
    - task: Bash@3
      displayName: Remove Docker Images from Agent
      inputs:
         targetType: 'inline'
         script: |
          echo "Remove Docker Images"
          docker rm $(REMOVE_CONTAINER)
          docker rmi jaibholecomputer374/test:$(CONSTAINER_REMOVED) --force
          docker rmi jaibholecomputer374/test:latest --force
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Push Docker Images on Docker Hub Repository
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'jaibholecomputer374/test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        addPipelineData: false
        addBaseImageData: false
        tags: |
          $(tag)
          latest

    - task: Bash@3
      displayName: Run the Docker Container
      inputs:
        targetType: 'inline'
        script: |
          echo "Run Docker Images"
          docker pull jaibholecomputer374/test:latest
          docker run -itd -p 8082:80 --name $(CONSTAINER_NAME) jaibholecomputer374/test:latest
          echo "access the port using 8082"    